# frozen_string_literal: true

source "https://rubygems.org"

# SEND PRS!!!

group :development, :test do
  # https://github.com/ruby/debug
  gem "debug"
end

# https://sorbet.org/docs/adopting
gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, :group => :development
